const list = [
  {
    Matricule: "212131087566",
    Nom: "Longar",
    Prénom: "Rafik",
    Mail: "rafiklongar000@gmail.com",
    Groupe: "03",
    Module: "Sid",
    Nature: "cc",
    Noter: "17",
    Notea: "09",
    des: true,
  },
  {
    Matricule: "212131093455",
    Nom: "Derbal",
    Prénom: "Tasser",
    Mail: "drbalyasser@gmail.com",
    Groupe: "01",
    Module: "Ihm",
    Nature: "Exmen",
    Noter: "15",
    Notea: "14",
    des: false,
  },
  {
    Matricule: "212131456755",
    Nom: "Ameur",
    Prénom: "Sidahmed",
    Mail: "ameursidahmed@gmail.com",
    Groupe: "02",
    Module: "Sad",
    Nature: "cc",
    Noter: "13",
    Notea: "14",
    des: true,
  },
  {
    Matricule: "212131087566",
    Nom: "Longar",
    Prénom: "Rafik",
    Mail: "rafiklongar000@gmail.com",
    Groupe: "03",
    Module: "Sid",
    Nature: "cc",
    Noter: "17",
    Notea: "09",
    des: false,
  },
  {
    Matricule: "212131055566",
    Nom: "Mezak",
    Prénom: "deboub",
    Mail: "deboubmerzak@gmail.com",
    Groupe: "03",
    Module: "Sid",
    Nature: "cc",
    Noter: "17",
    Notea: "09",
    des: false,
  },
];
export default list;
